// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxkosgidlkrbcesfvzso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4a29zZ2lkbGtyYmNlc2Z2enNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODUyOTgsImV4cCI6MjA2NzE2MTI5OH0.sPnTeueJxMqvFlTtnM5OdZULEqYMVeGDTES11G6-BuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});